Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/knl/dev/panopticon/panopticon/__main__.py", line 16, in <module>
    main()
  File "/home/knl/dev/panopticon/panopticon/__main__.py", line 13, in main
    print(ft.get_trace(), out=sys.stderr)
TypeError: 'out' is an invalid keyword argument for print()
